'use client'

import Link from 'next/link'
import { ChevronLeft, ChevronRight, LogOut, Menu, Shield, X } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { adminAuthService, useAdminStore, ADMIN_CONFIG } from '@/modules/admin'
import { adminNavigation } from '@/components/admin/AdminSidebarNavigation'

export default function AdminHeader({ collapsed, onToggleCollapse }: { collapsed: boolean; onToggleCollapse: () => void }) {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const { admin, clearAdmin } = useAdminStore()
  const handleLogout = async () => { try { await adminAuthService.logout(); clearAdmin(); toast.success('Logged out successfully'); window.location.href = ADMIN_CONFIG.ROUTES.LOGIN } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to sign out. Please try again.') } }
  const navigation = (iconOnly: boolean) => <nav className="flex-1 space-y-1 overflow-y-auto px-3 py-3">{adminNavigation.map(([href, label, Icon]) => <Link key={href} href={href} onClick={() => setIsMenuOpen(false)} title={iconOnly ? label : undefined} aria-label={iconOnly ? label : undefined} className={`flex items-center rounded-lg py-2.5 text-sm font-medium text-slate-300 transition hover:bg-slate-800 hover:text-white ${iconOnly ? 'justify-center px-2' : 'gap-3 px-3'}`}><Icon className="h-5 w-5 shrink-0" />{!iconOnly && label}</Link>)}</nav>
  const desktopMenu = <><div className={`flex items-center border-b border-slate-700 ${collapsed ? 'justify-center px-3 py-5' : 'justify-between px-4 py-4'}`}><Link href={ADMIN_CONFIG.ROUTES.DASHBOARD} title={collapsed ? 'MyThirumanam Admin' : undefined} className="flex min-w-0 items-center gap-2 text-lg font-bold text-white"><Shield className="h-6 w-6 shrink-0" />{!collapsed && <span className="truncate">MyThirumanam Admin</span>}</Link>{!collapsed && <Button variant="ghost" size="icon" aria-label="Collapse menu" className="shrink-0 text-slate-300 hover:bg-slate-800 hover:text-white" onClick={onToggleCollapse}><ChevronLeft className="h-5 w-5" /></Button>}</div>{collapsed && <div className="px-3 pt-3"><Button variant="ghost" size="icon" aria-label="Expand menu" className="w-full text-slate-300 hover:bg-slate-800 hover:text-white" onClick={onToggleCollapse}><ChevronRight className="h-5 w-5" /></Button></div>}{navigation(collapsed)}{admin && <div className={`border-t border-slate-700 p-4 ${collapsed ? 'flex justify-center' : ''}`}>{!collapsed && <><p className="truncate text-sm text-slate-300">{admin.email}</p><p className="mt-1 text-xs capitalize text-slate-400">{admin.role.replace('_', ' ')}</p></>}<Button variant="ghost" title={collapsed ? 'Logout' : undefined} aria-label={collapsed ? 'Logout' : undefined} className={`text-slate-300 hover:bg-slate-800 hover:text-white ${collapsed ? 'mt-0 size-10 p-0' : 'mt-3 w-full justify-start'}`} onClick={handleLogout}><LogOut className={collapsed ? 'h-5 w-5' : 'mr-2 h-4 w-4'} />{!collapsed && 'Logout'}</Button></div>}</>
  const mobileMenu = <><Link href={ADMIN_CONFIG.ROUTES.DASHBOARD} className="flex items-center gap-2 px-5 py-5 text-lg font-bold text-white"><Shield className="h-6 w-6" />MyThirumanam Admin</Link>{navigation(false)}{admin && <div className="border-t border-slate-700 p-4"><p className="truncate text-sm text-slate-300">{admin.email}</p><p className="mt-1 text-xs capitalize text-slate-400">{admin.role.replace('_', ' ')}</p><Button variant="ghost" className="mt-3 w-full justify-start text-slate-300 hover:bg-slate-800 hover:text-white" onClick={handleLogout}><LogOut className="mr-2 h-4 w-4" />Logout</Button></div>}</>
  return <><aside className={`fixed inset-y-0 left-0 z-40 hidden flex-col border-r border-slate-700 bg-slate-900 transition-[width] duration-200 md:flex ${collapsed ? 'w-20' : 'w-64'}`}>{desktopMenu}</aside><header className="sticky top-0 z-30 flex h-16 items-center border-b border-slate-700 bg-slate-900 px-4 text-white md:hidden"><Button variant="ghost" size="icon" className="text-slate-200 hover:bg-slate-800 hover:text-white" aria-label="Open admin menu" onClick={() => setIsMenuOpen(true)}><Menu className="h-6 w-6" /></Button><Link href={ADMIN_CONFIG.ROUTES.DASHBOARD} className="ml-3 flex items-center gap-2 font-bold"><Shield className="h-5 w-5" />MyThirumanam Admin</Link></header>{isMenuOpen && <div className="fixed inset-0 z-50 md:hidden"><button aria-label="Close admin menu" className="absolute inset-0 bg-slate-950/60" onClick={() => setIsMenuOpen(false)} /><aside className="relative flex h-full w-72 flex-col bg-slate-900 shadow-xl"><button aria-label="Close admin menu" className="absolute right-3 top-4 rounded-md p-2 text-slate-300 hover:bg-slate-800 hover:text-white" onClick={() => setIsMenuOpen(false)}><X className="h-5 w-5" /></button>{mobileMenu}</aside></div>}</>
}
