type BlogEmailSnapshot = { locale: 'en' | 'ta'; subject: string; preheader: string | null; headline: string; summary: string | null; targetUrl: string }

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]!)

export function renderBlogPublicationEmail(snapshot: BlogEmailSnapshot, unsubscribeUrl: string) {
  if (!unsubscribeUrl) throw new Error('An unsubscribe URL is required for campaign delivery.')
  const tamil = snapshot.locale === 'ta'
  const copy = tamil
    ? { label: 'புதிய வழிகாட்டி', read: 'முழு வழிகாட்டியை படிக்கவும்', planning: 'உங்கள் திருக்கடையூர் விழாவை திட்டமிடுங்கள்', prompt: 'உங்கள் விழாவை திட்டமிடுகிறீர்களா?', footer: 'சுயாதீன விழா திட்டமிடல் மற்றும் ஒருங்கிணைப்பு சேவை.', unsubscribe: 'மின்னஞ்சல் அறிவிப்புகளை நிறுத்த' }
    : { label: 'New Guide', read: 'Read the Full Guide', planning: 'Plan Your Thirukadaiyur Celebration', prompt: 'Planning your celebration?', footer: 'Independent celebration planning and coordination service.', unsubscribe: 'Unsubscribe' }
  const summary = snapshot.summary ? `<p style="margin:0 0 24px;color:#44403c;font-size:16px;line-height:26px">${escapeHtml(snapshot.summary)}</p>` : ''
  const preheader = snapshot.preheader ? `<span style="display:none;max-height:0;overflow:hidden">${escapeHtml(snapshot.preheader)}</span>` : ''
  const logoUrl = 'https://mythirumanam.in/brand/mythirumanam-logo.png'
  const targetUrl = escapeHtml(snapshot.targetUrl)
  const html = `${preheader}<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0;padding:0;background:#fffaf3"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:600px;background:#ffffff;border:1px solid #f1e5d3;border-radius:16px;overflow:hidden"><tr><td style="padding:28px 32px 24px;background:linear-gradient(135deg,#681c24,#8f2d2e);text-align:center"><img src="${logoUrl}" width="180" alt="MyThirumanam" style="display:block;width:180px;max-width:100%;height:auto;margin:0 auto 20px;border:0;outline:none;text-decoration:none"><p style="margin:0;color:#fde68a;font-family:Arial,sans-serif;font-size:12px;font-weight:700;letter-spacing:1.6px;text-transform:uppercase">${copy.label}</p></td></tr><tr><td style="padding:36px 32px 28px;font-family:Arial,sans-serif"><h1 style="margin:0 0 18px;color:#2c1810;font-size:29px;line-height:38px;font-weight:700">${escapeHtml(snapshot.headline)}</h1>${summary}<table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td style="border-radius:8px;background:#681c24"><a href="${targetUrl}" style="display:inline-block;padding:14px 20px;color:#ffffff;font-family:Arial,sans-serif;font-size:16px;font-weight:700;text-decoration:none">${copy.read}</a></td></tr></table></td></tr><tr><td style="padding:24px 32px;background:#fff7ed;border-top:1px solid #f1e5d3;font-family:Arial,sans-serif"><p style="margin:0 0 8px;color:#2c1810;font-size:18px;font-weight:700">${copy.prompt}</p><p style="margin:0"><a href="https://mythirumanam.in/plan" style="color:#8f2d2e;font-size:15px;font-weight:700;text-decoration:underline">${copy.planning}</a></p></td></tr><tr><td style="padding:24px 32px;background:#ffffff;font-family:Arial,sans-serif"><p style="margin:0 0 8px;color:#57534e;font-size:13px;line-height:20px">${copy.footer}</p><p style="margin:0"><a href="${escapeHtml(unsubscribeUrl)}" style="color:#78716c;font-size:12px;text-decoration:underline">${copy.unsubscribe}</a></p></td></tr></table></td></tr></table>`
  const text = ['MyThirumanam', copy.label, snapshot.headline, snapshot.summary ?? '', `${copy.read}: ${snapshot.targetUrl}`, copy.prompt, `${copy.planning}: https://mythirumanam.in/plan`, copy.footer, `${copy.unsubscribe}: ${unsubscribeUrl}`].filter(Boolean).join('\n\n')
  return { subject: snapshot.subject, html, text }
}
