import type { Metadata } from 'next'
import Link from 'next/link'
import { Heart, Search, ShieldCheck, UserPlus } from 'lucide-react'

const url = 'https://mythirumanam.in/matrimony'
export const metadata: Metadata = { title: 'Tamil Matrimony | MyThirumanam', description: 'Explore Tamil matrimonial profiles with profile creation, matching and search in a privacy-conscious, family-focused experience.', alternates: { canonical: url }, openGraph: { title: 'Tamil Matrimony | MyThirumanam', description: 'Explore Tamil matrimonial profiles with profile creation, matching and search in a privacy-conscious, family-focused experience.', url, siteName: 'MyThirumanam', type: 'website' } }

const journeys = [[Search, 'Find Matches', 'Browse matrimonial profiles using the existing search and preference experience.', '/search'], [UserPlus, 'Create Profile', 'Create a matrimonial profile and share the details that guide relevant introductions.', '/signup'], [Heart, 'Member Login', 'Return to your account, interests and profile controls.', '/login']] as const

export default function MatrimonyPage() {
  return <main className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-emerald-50 text-slate-900"><section className="mx-auto max-w-6xl px-4 py-20 sm:px-6 md:py-28"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-800">MyThirumanam Matrimony</p><h1 className="mt-4 max-w-3xl text-4xl font-bold leading-tight sm:text-5xl md:text-6xl">Discover compatible families</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">A family-focused matrimonial experience built around detailed profiles, preferences, privacy-conscious controls and thoughtful introductions.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/search" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-blue-800 px-6 py-3 font-bold text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-blue-800">Find Matches</Link><Link href="/signup" className="inline-flex min-h-12 items-center justify-center rounded-xl border-2 border-blue-700 px-6 py-3 font-bold text-blue-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-blue-800">Create Profile</Link><Link href="/login" className="inline-flex min-h-12 items-center justify-center rounded-xl px-6 py-3 font-bold text-slate-700 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-blue-800">Member Login</Link></div></section><section className="border-y border-slate-200 bg-white py-16"><div className="mx-auto grid max-w-6xl gap-6 px-4 sm:px-6 md:grid-cols-3">{journeys.map(([Icon, title, text, href]) => <article key={title} className="flex flex-col rounded-2xl border border-slate-200 p-6 shadow-sm"><Icon aria-hidden="true" className="h-7 w-7 text-blue-800" /><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-3 flex-1 leading-7 text-slate-600">{text}</p><Link href={href} className="mt-6 inline-flex min-h-11 items-center font-bold text-blue-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-blue-800">Continue to {title}</Link></article>)}</div></section><section className="mx-auto max-w-4xl px-4 py-16 text-center sm:px-6"><ShieldCheck aria-hidden="true" className="mx-auto h-9 w-9 text-emerald-700" /><h2 className="mt-4 text-3xl font-bold">A separate journey from Celebrations</h2><p className="mt-4 leading-7 text-slate-600">Matrimonial accounts and celebration enquiries remain separate. No matrimonial account is required to plan a Thirukadaiyur celebration.</p><Link href="/" className="mt-7 inline-flex min-h-11 items-center font-bold text-amber-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-amber-800">Explore Thirukadaiyur Celebrations</Link></section></main>
}
