import { BedDouble, Bus, Camera, Church, CircleEllipsis, Gift, Mail, Music2, Palette, Sparkles, UtensilsCrossed, Video, WandSparkles } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { getCelebrationServicePresentation, type PublicCelebrationService } from '@/lib/celebrations/service-query'
import { groupCelebrationServices } from '@/lib/celebrations/service-presentation'

const icons: Record<string, LucideIcon> = { priest: Church, pooja: Sparkles, venue: Church, temple: Church, food: UtensilsCrossed, decoration: Palette, camera: Camera, video: Video, music: Music2, hotel: BedDouble, transport: Bus, invitation: Mail, gift: Gift, complete: WandSparkles }
export function getCelebrationServiceIcon(icon: string | null) { return (icon && icons[icon]) || CircleEllipsis }
function serviceGroupHeadingId(name: string) { return `services-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}` }
export function CelebrationServices({ services }: { services: PublicCelebrationService[] }) {
  if (services.length === 0) return <p role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-stone-700">No celebration services are currently listed. Please try again shortly.</p>
  return <div className="space-y-8">{groupCelebrationServices(services).map((group) => { const headingId = serviceGroupHeadingId(group.name); return <section key={group.name} aria-labelledby={headingId}><div className="mb-4 flex flex-wrap items-baseline justify-between gap-2 border-b border-amber-200 pb-3"><h3 id={headingId} className="text-lg font-bold text-stone-900">{group.name}</h3><p className="text-sm font-medium text-amber-800">{group.services.length} {group.services.length === 1 ? 'service' : 'services'}</p></div><ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{group.services.map((service) => { const Icon = getCelebrationServiceIcon(service.icon); const presentation = getCelebrationServicePresentation(service); const isCompleteArrangement = service.code === 'complete_arrangement'; return <li key={service.id} className={`flex min-w-0 gap-3 rounded-2xl border bg-white p-4 shadow-sm ${isCompleteArrangement ? 'border-amber-400 ring-1 ring-amber-200' : 'border-amber-200'}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-800"><Icon aria-hidden="true" className="h-5 w-5" /></span><div className="min-w-0"><h4 className="break-words font-bold text-stone-900">{presentation.name}</h4>{presentation.description && <p className="mt-1 break-words text-sm leading-6 text-stone-600">{presentation.description}</p>}{isCompleteArrangement && <p className="mt-2 text-sm font-medium leading-6 text-amber-900">Need broader planning support? Choose Complete Arrangement when submitting your enquiry.</p>}</div></li> })}</ul></section> })}</div>
}
