import type { Metadata } from 'next'
import Link from 'next/link'
import { CelebrationBreadcrumbs } from '@/components/celebrations/CelebrationBreadcrumbs'
import { IndependentServiceNotice } from '@/components/celebrations/IndependentServiceNotice'
import { JsonLd } from '@/components/seo/JsonLd'
import { privacyPolicySections, tamilPrivacyIntroduction } from '@/lib/legal/privacy-policy'

const url = 'https://mythirumanam.in/privacy'
const description = 'Learn how MyThirumanam collects, uses and protects information provided for celebration planning and related services.'
export const metadata: Metadata = { title: 'Privacy Policy | MyThirumanam', description, alternates: { canonical: url }, openGraph: { title: 'Privacy Policy | MyThirumanam', description, url, siteName: 'MyThirumanam', type: 'website' } }

export default function PrivacyPage() {
  return <><JsonLd data={{ '@context': 'https://schema.org', '@type': 'WebPage', name: 'Privacy Policy', url, description }} /><main className="min-h-screen bg-[#fffaf3] text-stone-900"><div className="mx-auto max-w-4xl px-4 sm:px-6"><CelebrationBreadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Privacy Policy' }]} /></div><section className="mx-auto max-w-4xl px-4 pb-16 pt-4 sm:px-6 sm:pb-20"><div className="rounded-3xl border border-amber-200 bg-white p-6 shadow-sm sm:p-10"><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-800">Legal information</p><h1 className="mt-3 text-3xl font-bold sm:text-4xl">Privacy Policy</h1><p className="mt-5 leading-8 text-stone-700">MyThirumanam respects your privacy and aims to handle personal information responsibly. This Privacy Policy explains how information is collected, used and handled when you use MyThirumanam&apos;s celebration-planning and related services.</p><p lang="ta" className="mt-4 leading-8 text-stone-700">{tamilPrivacyIntroduction}</p><div className="mt-6 space-y-3"><IndependentServiceNotice variant="full" /><IndependentServiceNotice locale="ta" variant="full" /></div></div><div className="mt-8 space-y-5">{privacyPolicySections.map(([title, text]) => <section key={title} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-stone-700">{text}</p></section>)}</div><section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-xl font-semibold">Privacy and grievance contact</h2><p className="mt-3 leading-7 text-stone-700">For service concerns, privacy requests, correction or deletion requests, and grievances, use our customer contact page. Approved privacy and grievance contact details are required before production publication.</p><Link href="/contact" className="mt-4 inline-flex font-semibold text-amber-800 underline">Contact MyThirumanam</Link></section><p className="mt-8 text-sm leading-6 text-stone-600">Tamil legal wording should receive professional review before launch.</p></section></main></>
}
