export const privacyPolicySections = [
  ['Information we collect', 'For celebration planning, we may collect couple and celebration information such as names, dates of birth, ceremony preferences, and optional nakshatra or rasi details; planning information such as dates, guest-count range, travel location, requested services and notes; and contact information such as name, mobile number, email, relationship and preferred contact method.'],
  ['How we use information', 'We use this information to understand and respond to planning enquiries, coordinate requested event-related services, communicate with customers, maintain enquiry records, prevent abuse or security incidents, and comply with applicable legal obligations where necessary.'],
  ['Optional astrology information', 'Nakshatra and rasi details are optional. Where provided, they are used only in the celebration-planning context for which they were provided, not for advertising, unrelated profiling or Matrimony matching.'],
  ['Service-provider sharing', 'Where necessary to arrange a service requested by you, relevant information may be shared with the service provider involved in fulfilling that requirement, such as accommodation, catering, transportation, photography, videography, decoration or Vadhyar/priest providers. These providers are independent service providers. Information is not automatically shared with temple authorities.'],
  ['Temple independence', 'MyThirumanam is an independent event-management and coordination service. We do not represent temple authorities or provide direct temple contact. Temple permissions, timings, fees and facilities remain subject to the respective temple authorities.'],
  ['Security and technical information', 'We use technical and organizational measures intended to protect information against unauthorized access, misuse or disclosure. We may process limited technical information needed to protect forms from automated abuse, including through security and anti-abuse providers.'],
  ['Cookies and third parties', 'MyThirumanam uses essential authentication cookies for account features. Celebration forms may use Cloudflare Turnstile to help prevent automated abuse. We do not currently operate analytics or advertising pixels on the public Celebrations experience.'],
  ['Retention', 'We retain personal information only for as long as reasonably necessary for the purposes described in this policy, subject to applicable legal, accounting and operational requirements.'],
  ['Correction, deletion and privacy requests', 'You may ask MyThirumanam to correct or update inaccurate information, request deletion where applicable, or seek privacy-related assistance. Requests are handled subject to applicable legal and operational requirements.'],
  ['Matrimony', 'Matrimony may process separate account, profile, photo, preference, search, match and interest information. A dedicated Matrimony privacy review remains required before this policy is treated as a complete description of that product. Account deletion workflow also requires product implementation and review.'],
] as const

export const tamilPrivacyIntroduction = 'MyThirumanam உங்கள் தனியுரிமையை மதிக்கிறது; தனிப்பட்ட தகவல்களை பொறுப்புடன் கையாள முயல்கிறது. இந்த தனியுரிமைக் கொள்கை, MyThirumanam-ன் விழா திட்டமிடல் மற்றும் தொடர்புடைய சேவைகளைப் பயன்படுத்தும் போது தகவல்கள் எவ்வாறு சேகரிக்கப்படுகின்றன, பயன்படுத்தப்படுகின்றன மற்றும் கையாளப்படுகின்றன என்பதை விளக்குகிறது. MyThirumanam ஒரு சுயாதீன விழா ஏற்பாடு மற்றும் ஒருங்கிணைப்பு சேவையாகும்; இது எந்தக் கோவிலின் அதிகாரப்பூர்வ அல்லது அங்கீகரிக்கப்பட்ட இணையதளமும் அல்ல.'
